os:
  osx

before_install:
  - export CMDPWD=`pwd`
  - brew update
  - brew install ghc
  - brew install agda
  - mkdir -p ~/.agda
  - echo /usr/local/lib/agda/standard-library.agda-lib >>~/.agda/libraries
  - cd /usr/local/lib/
  - git clone http://github.com/jonaprieto/agda-prop.git
  - echo /usr/local/lib/agda-prop/agda-prop.agda-lib >>~/.agda/libraries
  - echo agda-prop >>~/.agda/defaults
  - cd $CMDPWD

script:
  - agda src/ATP/Metis.agda
